# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "vaswopw-yx98322"
user = "NCREFF"
password = "Synergy23@"
role = "ACCOUNTADMIN"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
